name: Zoho CRM Bulk Data Processor Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    environment: Production
    name: 'Creating Zoho CRM Bulk Data Processor Release'
    runs-on: ubuntu-latest

    steps:
      - name: Cloning repository
        uses: actions/checkout@v2

      - name: Installing Node 20
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Installing Catalyst CLI
        run: npm i -g zcatalyst-cli@1.21.0

      - name: Installing dependencies for bulkdataprocessor
        working-directory: ./functions/bulkdataprocessor
        run: npm install --omit=dev

      - name: Installing dependencies for bulkjobscheduler
        working-directory: ./functions/bulkjobscheduler
        run: npm install --omit=dev

      - name: Installing dependencies for zohocrm_bulk_callback
        working-directory: ./functions/zohocrm_bulk_callback
        run: npm install --omit=dev

      - name: Creating release directory
        run: mkdir -p release/functions

      - name: Zipping bulkdataprocessor
        working-directory: ./functions/bulkdataprocessor
        run: zip -r ../../release/functions/bulkdataprocessor.zip .

      - name: Zipping bulkjobscheduler
        working-directory: ./functions/bulkjobscheduler
        run: zip -r ../../release/functions/bulkjobscheduler.zip .

      - name: Zipping zohocrm_bulk_callback
        working-directory: ./functions/zohocrm_bulk_callback
        run: zip -r ../../release/functions/zohocrm_bulk_callback.zip .

      - name: Copying project template
        run: cp project-template-1.0.0.json release/project-template-1.0.0.json

      - name: Generating release zip
        run: cd release && zip -r release.zip .

      - name: Generating artifacts
        uses: ncipollo/release-action@v1
        with:
          draft: true
          tag: ${{ env.RELEASE_VERSION }}
          artifacts: "./release/release.zip"
